# CI/sonar-project.properties
sonar.projectKey=secure-task-app
sonar.projectName=Secure Task App
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.pylint.reportPath=pylint-report.txt
sonar.python.bandit.reportPath=bandit-report.json

sonar.exclusions=**/venv/**,**/tests/**
sonar.coverage.exclusions=**/tests/**,**/__pycache__/**

sonar.sourceEncoding=UTF-8
