version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://bankuser:bankpass@db:5432/bankdb
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key
      JWT_SECRET_KEY: your-jwt-secret
    volumes:
      - ./app:/app/app
   
   falco:
    image: falcosecurity/falco-no-driver:latest
    container_name: falco
    privileged: true                        # Required — Falco needs kernel access
    pid: host                               # Access host PID namespace
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock   # Docker socket
      - /proc:/host/proc:ro                              # Host proc fs
      - /boot:/host/boot:ro                              # Kernel info
      - /lib/modules:/host/lib/modules:ro                # Kernel modules
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      - ./falco/custom_rules.yaml:/etc/falco/rules.d/custom_rules.yaml:ro
    environment:
      - FALCO_GRPC_ENABLED=true
      - FALCO_GRPC_BIND_ADDRESS=0.0.0.0:5060
    command: >
      falco
      --rules-file /etc/falco/falco_rules.yaml
      --rules-file /etc/falco/rules.d/custom_rules.yaml
      -o json_output=true
      -o log_stderr=true
    restart: unless-stopped
    networks:
      - your_network_name       # ← replace with your actual network name   

volumes:
  postgres_data:
